import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'sonner';
import Navbar from '@/app/_ui/Navbar';
import Providers from '@/app/_utils/Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`h-full antialiased`}>
      <body className='min-h-full flex flex-col'>
        <section className='h-screen dark:bg-black'>
          <Navbar />
          <main className='grid grid-cols-1 place-items-center text-center'>
            <Providers>{children}</Providers>
            <Toaster />
          </main>
        </section>
      </body>
    </html>
  );
}
